name       : python-zope.deferredimport
version    : '4.4'
release    : 7
source     :
    - https://github.com/zopefoundation/zope.deferredimport/archive/refs/tags/4.4.tar.gz : a6091c9cbdd7ebfe3b8c340da524e18864f20e957eed8aa8bc5d517fddc12577
license    : ZPL-2.1
component  : programming.python
summary    : Defer imports until used by code
description: |
    Often, especially for package modules, you want to import names for convenience, but not actually perform the imports until necessary. The zope.deferredimport package provided facilities for defining names in modules that will be imported from somewhere else when used. You can also cause deprecation warnings to be issued when a variable is used.
rundeps    :
    - python-zope.proxy
build      : |
    %python3_setup
install    : |
    %python3_install
