name       : python-zope.deferredimport
version    : 4.3
release    : 2
source     :
    - https://github.com/zopefoundation/zope.deferredimport/archive/4.3.tar.gz : abd06dc079952c687024d55fb9a5b416a5544ae48f54a27495738d73169154be
license    : ZPL-2.1
component  : programming.python
summary    : Defer imports until used by code
description: |
    Often, especially for package modules, you want to import names for convenience, but not actually perform the imports until necessary. The zope.deferredimport package provided facilities for defining names in modules that will be imported from somewhere else when used. You can also cause deprecation warnings to be issued when a variable is used.
builddeps  :
    - python-setuptools
rundeps    :
    - python-zope.proxy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
